app = "burning-airlines"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "dockerfile"

[env]
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "true"
  DEMO_MODE = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"

    [http_service.checks.headers]
      Host = "burning-airlines.fly.dev"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
