default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: 5432
  database: burning_airlines
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: burning_airlines
  host: localhost

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: 5432
  database: burning_airlines
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
